import 'dart:math';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_star/star.dart';
import 'package:flutter_star/star_score.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:widget_repository/widget_repository.dart';
import 'package:fx_env/fx_env.dart';
import 'package:widget_ui/widget_ui.dart';

class WidgetLogo extends StatelessWidget {
  final Color background;
  final String widgetName;
  final int? widgetId;
  final double lever;
  final bool inDetail;

  const WidgetLogo({
    super.key,
    required this.background,
    required this.widgetName,
    this.widgetId,
    required this.lever,
    this.inDetail = false,
  });

  @override
  Widget build(BuildContext context) {
    return Stack(
      children: [
        Container(
          width: 110,
          height: 110,
          alignment: Alignment.center,
          decoration: BoxDecoration(
            color: background,
            gradient: LinearGradient(
                transform: const GradientRotation(270 * 180 / pi),
                colors: [
                  background.withValues(alpha: 0.9),
                  background.withValues(alpha: 0.5)
                ]),
            borderRadius: inDetail
                ? BorderRadius.circular(6)
                : const BorderRadius.only(
                    topLeft: Radius.circular(6),
                    bottomLeft: Radius.circular(6)),
          ),
          child: SvgPicture.asset(
            'assets/images/widgets/${widgetLogo(widgetName)}',
            width: 80,
          ),
        ),
        Positioned(
            bottom: 4,
            left: 6,
            child: WidgetIdView(
              id: widgetId ?? 0,
            )),
        Positioned(
          top: 6,
          right: -4,
          child: StarScore(
            score: lever,
            star: Star(size: 10, fillColor: Colors.white),
          ),
        ),
        if (widgetId != null) _buildFieldCountBadge(context),
      ],
    );
  }

  Widget _buildFieldCountBadge(BuildContext context) {
    final provider = WidgetStatisticsProvider();
    final stats = provider.statistics;
    if (stats == null) return const SizedBox.shrink();

    final fieldCount = stats.getWidgetFieldCount(widgetId!);
    if (fieldCount == 0) return const SizedBox.shrink();

    return Positioned(
      right: 0,
      bottom: 0,
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onTap: () => _showFieldsDialog(context),
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 6.0, vertical: 4),
          child: Text(
            '属性:$fieldCount',
            style: const TextStyle(
              fontSize: 10,
              color: Colors.white,
              decoration: TextDecoration.underline,
              decorationColor: Colors.white,
            ),
          ),
        ),
      ),
    );
  }

  void _showFieldsDialog(BuildContext context) {
    if (kApp.isMobile) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) => WidgetFieldsPage(
            widgetId: widgetId!,
            widgetName: widgetName,
          ),
        ),
      );
    } else {
      showDialog(
        context: context,
        builder: (context) => WidgetFieldsDialog(
          widgetId: widgetId!,
          widgetName: widgetName,
        ),
      );
    }
  }
}

String widgetLogo(String widgetName) {
  return switch (widgetName) {
    'Container' => 'Container.svg',
    'Text' => 'Text.svg',
    'GestureDetector' => 'GestureDetector.svg',
    'CircleAvatar' => 'CircleAvatar.svg',
    'Card' => 'Card.svg',
    'ListView' => 'ListView.svg',
    'GridView' => 'GridView.svg',
    'SingleChildScrollView' => 'SingleChildScrollView.svg',
    'PageView' => 'PageView.svg',
    'InputChip' => 'InputChip.svg',
    'Chip' => 'Chip.svg',
    'FilterChip' => 'FilterChip.svg',
    'MaterialButton' => 'MaterialButton.svg',
    'FlutterLogo' => 'FlutterLogo.svg',
    'RichText' => 'RichText.svg',
    'FloatingActionButton' => 'FloatingActionButton.svg',
    'Banner' => 'Banner.svg',
    'Icon' => 'Icon.svg',
    'ImageIcon' => 'ImageIcon.svg',
    'FadeInImage' => 'FadeInImage.svg',
    'Visibility' => 'Visibility.svg',
    'SliverVisibility' => 'SliverVisibility.svg',
    'TooltipVisibility' => 'TooltipVisibility.svg',
    'ChoiceChip' => 'ChoiceChip.svg',
    'ActionChip' => 'ActionChip.svg',
    'RawChip' => 'RawChip.svg',
    'ChipTheme' => 'ChipTheme.svg',
    'ListTile' => 'ListTile.svg',
    'CheckboxListTile' => 'CheckboxListTile.svg',
    'SwitchListTile' => 'SwitchListTile.svg',
    'RadioListTile' => 'RadioListTile.svg',
    'AboutListTile' => 'AboutListTile.svg',
    'ListTileTheme' => 'ListTileTheme.svg',
    'CupertinoListTile' => 'CupertinoListTile.svg',
    'CupertinoListTileChevron' => 'CupertinoListTileChevron.svg',
    'GridTileBar' => 'GridTileBar.svg',
    'GridTile' => 'GridTile.svg',
    'GridPaper' => 'GridPaper.svg',
    'SliverGrid' => 'SliverGrid.svg',
    'AnimatedGrid' => 'AnimatedGrid.svg',
    'SliverAnimatedGrid' => 'SliverAnimatedGrid.svg',
    'CupertinoButton' => 'CupertinoButton.svg',
    'RawMaterialButton' => 'RawMaterialButton.svg',
    'TextButton' => 'TextButton.svg',
    'ElevatedButton' => 'ElevatedButton.svg',
    'OutlinedButton' => 'OutlinedButton.svg',
    'FilledButton' => 'FilledButton.svg',
    'ButtonStyleButton' => 'ButtonStyleButton.svg',
    'IconButton' => 'IconButton.svg',
    'BackButton' => 'BackButton.svg',
    'CloseButton' => 'CloseButton.svg',
    'BackButtonIcon' => 'BackButtonIcon.svg',
    'CloseButtonIcon' => 'CloseButtonIcon.svg',
    'DrawerButtonIcon' => 'DrawerButtonIcon.svg',
    'EndDrawerButtonIcon' => 'EndDrawerButtonIcon.svg',
    'DrawerButton' => 'DrawerButton.svg',
    'EndDrawerButton' => 'EndDrawerButton.svg',
    'CupertinoNavigationBarBackButton' => 'CupertinoNavigationBarBackButton.svg',
    'InspectorButton' => 'InspectorButton.svg',
    'ButtonBar' => 'ButtonBar.svg',
    'ToggleButtons' => 'ToggleButtons.svg',
    'DropdownButton' => 'DropdownButton.svg',
    'PopupMenuButton' => 'PopupMenuButton.svg',
    'DropdownButtonHideUnderline' => 'DropdownButtonHideUnderline.svg',
    'DropdownButtonFormField' => 'DropdownButtonFormField.svg',
    'CheckboxMenuButton' => 'CheckboxMenuButton.svg',
    'RadioMenuButton' => 'RadioMenuButton.svg',
    'MenuItemButton' => 'MenuItemButton.svg',
    'SubmenuButton' => 'SubmenuButton.svg',
    'SegmentedButton' => 'SegmentedButton.svg',
    'BackButtonListener' => 'BackButtonListener.svg',
    'ButtonTheme' => 'ButtonTheme.svg',
    'ToggleButtonsTheme' => 'ToggleButtonsTheme.svg',
    'ButtonBarTheme' => 'ButtonBarTheme.svg',
    'ElevatedButtonTheme' => 'ElevatedButtonTheme.svg',
    'FilledButtonTheme' => 'FilledButtonTheme.svg',
    'IconButtonTheme' => 'IconButtonTheme.svg',
    'MenuButtonTheme' => 'MenuButtonTheme.svg',
    'OutlinedButtonTheme' => 'OutlinedButtonTheme.svg',
    'SegmentedButtonTheme' => 'SegmentedButtonTheme.svg',
    'TextButtonTheme' => 'TextButtonTheme.svg',
    'CupertinoDesktopTextSelectionToolbarButton' => 'CupertinoDesktopTextSelectionToolbarButton.svg',
    'CupertinoTextSelectionToolbarButton' => 'CupertinoTextSelectionToolbarButton.svg',
    'DesktopTextSelectionToolbarButton' => 'DesktopTextSelectionToolbarButton.svg',
    'TextSelectionToolbarTextButton' => 'TextSelectionToolbarTextButton.svg',
    'UserAccountsDrawerHeader' => 'UserAccountsDrawerHeader.svg',
    'Divider' => 'Divider.svg',
    'VerticalDivider' => 'VerticalDivider.svg',
    'Placeholder' => 'Placeholder.svg',
    'Image' => 'Image.svg',
    'Checkbox' => 'Checkbox.svg',
    'Switch' => 'Switch.svg',
    'CupertinoSwitch' => 'CupertinoSwitch.svg',
    'Slider' => 'Slider.svg',
    'CupertinoSlider' => 'CupertinoSlider.svg',
    'RangeSlider' => 'RangeSlider.svg',
    'Radio' => 'Radio.svg',
    'SelectableText' => 'SelectableText.svg',
    'TextField' => 'TextField.svg',
    'DefaultTextStyleTransition' => 'DefaultTextStyleTransition.svg',
    'AnimatedDefaultTextStyle' => 'AnimatedDefaultTextStyle.svg',
    'TextFormField' => 'TextFormField.svg',
    'EditableText' => 'EditableText.svg',
    'CupertinoTextField' => 'CupertinoTextField.svg',
    'TextFieldTapRegion' => 'TextFieldTapRegion.svg',
    'DefaultTextStyle' => 'DefaultTextStyle.svg',
    'CupertinoSearchTextField' => 'CupertinoSearchTextField.svg',
    'CupertinoTextFormFieldRow' => 'CupertinoTextFormFieldRow.svg',
    'DefaultTextEditingShortcuts' => 'DefaultTextEditingShortcuts.svg',
    'DefaultTextHeightBehavior' => 'DefaultTextHeightBehavior.svg',
    'CupertinoTextSelectionToolbar' => 'CupertinoTextSelectionToolbar.svg',
    'AdaptiveTextSelectionToolbar' => 'AdaptiveTextSelectionToolbar.svg',
    'CupertinoAdaptiveTextSelectionToolbar' => 'CupertinoAdaptiveTextSelectionToolbar.svg',
    'CupertinoDesktopTextSelectionToolbar' => 'CupertinoDesktopTextSelectionToolbar.svg',
    'CupertinoTextMagnifier' => 'CupertinoTextMagnifier.svg',
    'DesktopTextSelectionToolbar' => 'DesktopTextSelectionToolbar.svg',
    'TextMagnifier' => 'TextMagnifier.svg',
    'TextSelectionGestureDetector' => 'TextSelectionGestureDetector.svg',
    'TextSelectionTheme' => 'TextSelectionTheme.svg',
    'TextSelectionToolbar' => 'TextSelectionToolbar.svg',
    'CupertinoContextMenu' => 'CupertinoContextMenu.svg',
    'CupertinoContextMenuAction' => 'CupertinoContextMenuAction.svg',
    'PlatformSelectableRegionContextMenu' => 'PlatformSelectableRegionContextMenu.svg',
    'SystemContextMenu' => 'SystemContextMenu.svg',
    'Texture' => 'Texture.svg',
    'AppBar' => 'AppBar.svg',
    'TabBar' => 'TabBar.svg',
    'TabBarView' => 'TabBarView.svg',
    'BottomNavigationBar' => 'BottomNavigationBar.svg',
    'BottomAppBar' => 'BottomAppBar.svg',
    'CupertinoNavigationBar' => 'CupertinoNavigationBar.svg',
    'CupertinoTabBar' => 'CupertinoTabBar.svg',
    'SliverAppBar' => 'SliverAppBar.svg',
    'FlexibleSpaceBar' => 'FlexibleSpaceBar.svg',
    'NavigationToolbar' => 'NavigationToolbar.svg',
    'CupertinoSliverNavigationBar' => 'CupertinoSliverNavigationBar.svg',
    'BottomNavigationBarTheme' => 'BottomNavigationBarTheme.svg',
    'FlexibleSpaceBarSettings' => 'FlexibleSpaceBarSettings.svg',
    'TabBarTheme' => 'TabBarTheme.svg',
    'SnackBar' => 'SnackBar.svg',
    'SnackBarAction' => 'SnackBarAction.svg',
    'Scrollbar' => 'Scrollbar.svg',
    'CupertinoScrollbar' => 'CupertinoScrollbar.svg',
    'ModalBarrier' => 'ModalBarrier.svg',
    'AnimatedModalBarrier' => 'AnimatedModalBarrier.svg',
    'RawScrollbar' => 'RawScrollbar.svg',
    'ScrollbarTheme' => 'ScrollbarTheme.svg',
    'OverflowBar' => 'OverflowBar.svg',
    'CupertinoSpellCheckSuggestionsToolbar' => 'CupertinoSpellCheckSuggestionsToolbar.svg',
    'MenuBar' => 'MenuBar.svg',
    'MenuBarTheme' => 'MenuBarTheme.svg',
    'NavigationBar' => 'NavigationBar.svg',
    'NavigationBarTheme' => 'NavigationBarTheme.svg',
    'PlatformMenuBar' => 'PlatformMenuBar.svg',
    'SearchBar' => 'SearchBar.svg',
    'SearchBarTheme' => 'SearchBarTheme.svg',
    'SpellCheckSuggestionsToolbar' => 'SpellCheckSuggestionsToolbar.svg',
    'CircularProgressIndicator' => 'CircularProgressIndicator.svg',
    'LinearProgressIndicator' => 'LinearProgressIndicator.svg',
    'ProgressIndicator' => 'ProgressIndicator.svg',
    'ProgressIndicatorTheme' => 'ProgressIndicatorTheme.svg',
    'RefreshProgressIndicator' => 'RefreshProgressIndicator.svg',
    'ExpandIcon' => 'ExpandIcon.svg',
    'AnimatedIcon' => 'AnimatedIcon.svg',
    'ActionIconTheme' => 'ActionIconTheme.svg',
    'IconTheme' => 'IconTheme.svg',
    'ClipOval' => 'ClipOval.svg',
    'ClipRect' => 'ClipRect.svg',
    'ClipRRect' => 'ClipRRect.svg',
    'ClipPath' => 'ClipPath.svg',
    'ClipRSuperellipse' => 'ClipRSuperellipse.svg',
    'DecoratedBox' => 'DecoratedBox.svg',
    'RotatedBox' => 'RotatedBox.svg',
    'SizedBox' => 'SizedBox.svg',
    'LimitedBox' => 'LimitedBox.svg',
    'ConstrainedBox' => 'ConstrainedBox.svg',
    'UnconstrainedBox' => 'UnconstrainedBox.svg',
    'FractionallySizedBox' => 'FractionallySizedBox.svg',
    'OverflowBox' => 'OverflowBox.svg',
    'SizedOverflowBox' => 'SizedOverflowBox.svg',
    'FittedBox' => 'FittedBox.svg',
    'DecoratedBoxTransition' => 'DecoratedBoxTransition.svg',
    'SliverToBoxAdapter' => 'SliverToBoxAdapter.svg',
    'CupertinoCheckbox' => 'CupertinoCheckbox.svg',
    'AnimatedFractionallySizedBox' => 'AnimatedFractionallySizedBox.svg',
    'ColoredBox' => 'ColoredBox.svg',
    'BoxScrollView' => 'BoxScrollView.svg',
    'CheckboxTheme' => 'CheckboxTheme.svg',
    'ConstraintsTransformBox' => 'ConstraintsTransformBox.svg',
    'SliverMultiBoxAdaptorWidget' => 'SliverMultiBoxAdaptorWidget.svg',
    'WidgetToRenderBoxAdapter' => 'WidgetToRenderBoxAdapter.svg',
    'Dialog' => 'Dialog.svg',
    'AlertDialog' => 'AlertDialog.svg',
    'SimpleDialog' => 'SimpleDialog.svg',
    'CupertinoAlertDialog' => 'CupertinoAlertDialog.svg',
    'AboutDialog' => 'AboutDialog.svg',
    'SimpleDialogOption' => 'SimpleDialogOption.svg',
    'CupertinoFullscreenDialogTransition' => 'CupertinoFullscreenDialogTransition.svg',
    'DateRangePickerDialog' => 'DateRangePickerDialog.svg',
    'CupertinoDialogAction' => 'CupertinoDialogAction.svg',
    'DatePickerDialog' => 'DatePickerDialog.svg',
    'DialogTheme' => 'DialogTheme.svg',
    'TimePickerDialog' => 'TimePickerDialog.svg',
    'CupertinoActivityIndicator' => 'CupertinoActivityIndicator.svg',
    'CupertinoActionSheet' => 'CupertinoActionSheet.svg',
    'CupertinoActionSheetAction' => 'CupertinoActionSheetAction.svg',
    'CupertinoDatePicker' => 'CupertinoDatePicker.svg',
    'CupertinoTimerPicker' => 'CupertinoTimerPicker.svg',
    'CupertinoPicker' => 'CupertinoPicker.svg',
    'CupertinoApp' => 'CupertinoApp.svg',
    'CupertinoPageScaffold' => 'CupertinoPageScaffold.svg',
    'CupertinoTabScaffold' => 'CupertinoTabScaffold.svg',
    'CupertinoTheme' => 'CupertinoTheme.svg',
    'CupertinoPageTransition' => 'CupertinoPageTransition.svg',
    'CupertinoPopupSurface' => 'CupertinoPopupSurface.svg',
    'CupertinoTabView' => 'CupertinoTabView.svg',
    'CupertinoRadio' => 'CupertinoRadio.svg',
    'CupertinoSlidingSegmentedControl' => 'CupertinoSlidingSegmentedControl.svg',
    'CupertinoSegmentedControl' => 'CupertinoSegmentedControl.svg',
    'CupertinoSliverRefreshControl' => 'CupertinoSliverRefreshControl.svg',
    'CupertinoUserInterfaceLevel' => 'CupertinoUserInterfaceLevel.svg',
    'CupertinoFormRow' => 'CupertinoFormRow.svg',
    'CupertinoFormSection' => 'CupertinoFormSection.svg',
    'CupertinoListSection' => 'CupertinoListSection.svg',
    'CupertinoMagnifier' => 'CupertinoMagnifier.svg',
    'CupertinoPageScaffoldBackgroundColor' => 'CupertinoPageScaffoldBackgroundColor.svg',
    'CupertinoPickerDefaultSelectionOverlay' => 'CupertinoPickerDefaultSelectionOverlay.svg',
    'CupertinoSheetTransition' => 'CupertinoSheetTransition.svg',
    'InheritedCupertinoTheme' => 'InheritedCupertinoTheme.svg',
    'AnimatedCrossFade' => 'AnimatedCrossFade.svg',
    'AnimatedSwitcher' => 'AnimatedSwitcher.svg',
    'AnimatedList' => 'AnimatedList.svg',
    'AnimatedOpacity' => 'AnimatedOpacity.svg',
    'AnimatedPadding' => 'AnimatedPadding.svg',
    'AnimatedAlign' => 'AnimatedAlign.svg',
    'AnimatedPositioned' => 'AnimatedPositioned.svg',
    'AnimatedPositionedDirectional' => 'AnimatedPositionedDirectional.svg',
    'AnimatedContainer' => 'AnimatedContainer.svg',
    'AnimatedSize' => 'AnimatedSize.svg',
    'AnimatedTheme' => 'AnimatedTheme.svg',
    'AnimatedPhysicalModel' => 'AnimatedPhysicalModel.svg',
    'AnimatedBuilder' => 'AnimatedBuilder.svg',
    'AnimatedSlide' => 'AnimatedSlide.svg',
    'AnimatedScale' => 'AnimatedScale.svg',
    'AnimatedRotation' => 'AnimatedRotation.svg',
    'SliverAnimatedList' => 'SliverAnimatedList.svg',
    'AnimatedWidget' => 'AnimatedWidget.svg',
    'ImplicitlyAnimatedWidget' => 'ImplicitlyAnimatedWidget.svg',
    'SliverAnimatedOpacity' => 'SliverAnimatedOpacity.svg',
    'RefreshIndicator' => 'RefreshIndicator.svg',
    'Tooltip' => 'Tooltip.svg',
    'ExpansionTile' => 'ExpansionTile.svg',
    'Scaffold' => 'Scaffold.svg',
    'MaterialApp' => 'MaterialApp.svg',
    'Offstage' => 'Offstage.svg',
    'Opacity' => 'Opacity.svg',
    'Padding' => 'Padding.svg',
    'Baseline' => 'Baseline.svg',
    'AspectRatio' => 'AspectRatio.svg',
    'Transform' => 'Transform.svg',
    'Align' => 'Align.svg',
    'Center' => 'Center.svg',
    'ColorFiltered' => 'ColorFiltered.svg',
    'FadeTransition' => 'FadeTransition.svg',
    'RotationTransition' => 'RotationTransition.svg',
    'ScaleTransition' => 'ScaleTransition.svg',
    'SizeTransition' => 'SizeTransition.svg',
    'PositionedTransition' => 'PositionedTransition.svg',
    'Flex' => 'Flex.svg',
    'Row' => 'Row.svg',
    'Column' => 'Column.svg',
    'Stack' => 'Stack.svg',
    'Wrap' => 'Wrap.svg',
    'Flow' => 'Flow.svg',
    'DataTable' => 'DataTable.svg',
    'Draggable' => 'Draggable.svg',
    'DragTarget' => 'DragTarget.svg',
    'LongPressDraggable' => 'LongPressDraggable.svg',
    'Expanded' => 'Expanded.svg',
    'Spacer' => 'Spacer.svg',
    'Positioned' => 'Positioned.svg',
    'Flexible' => 'Flexible.svg',
    'Table' => 'Table.svg',
    'AlignTransition' => 'AlignTransition.svg',
    'SlideTransition' => 'SlideTransition.svg',
    'RelativePositionedTransition' => 'RelativePositionedTransition.svg',
    'YearPicker' => 'YearPicker.svg',
    'BottomSheet' => 'BottomSheet.svg',
    'LicensePage' => 'LicensePage.svg',
    'Listener' => 'Listener.svg',
    'Tab' => 'Tab.svg',
    'InkResponse' => 'InkResponse.svg',
    'InkWell' => 'InkWell.svg',
    'TableRowInkWell' => 'TableRowInkWell.svg',
    'Ink' => 'Ink.svg',
    'Drawer' => 'Drawer.svg',
    'DrawerHeader' => 'DrawerHeader.svg',
    'PositionedDirectional' => 'PositionedDirectional.svg',
    'Material' => 'Material.svg',
    'IndexedStack' => 'IndexedStack.svg',
    'CustomPaint' => 'CustomPaint.svg',
    'MediaQuery' => 'MediaQuery.svg',
    'Theme' => 'Theme.svg',
    'WillPopScope' => 'WillPopScope.svg',
    'Hero' => 'Hero.svg',
    'FutureBuilder' => 'FutureBuilder.svg',
    'StreamBuilder' => 'StreamBuilder.svg',
    'PopupMenuDivider' => 'PopupMenuDivider.svg',
    'Dismissible' => 'Dismissible.svg',
    'ReorderableListView' => 'ReorderableListView.svg',
    'ExpansionPanelList' => 'ExpansionPanelList.svg',
    'ListWheelScrollView' => 'ListWheelScrollView.svg',
    'ScrollConfiguration' => 'ScrollConfiguration.svg',
    'Overlay' => 'Overlay.svg',
    'CustomScrollView' => 'CustomScrollView.svg',
    'SliverList' => 'SliverList.svg',
    'SliverFixedExtentList' => 'SliverFixedExtentList.svg',
    'SliverFillViewport' => 'SliverFillViewport.svg',
    'SliverPersistentHeader' => 'SliverPersistentHeader.svg',
    'SliverPadding' => 'SliverPadding.svg',
    'SliverOpacity' => 'SliverOpacity.svg',
    'ErrorWidget' => 'ErrorWidget.svg',
    'Form' => 'Form.svg',
    'Stepper' => 'Stepper.svg',
    'Builder' => 'Builder.svg',
    'OrientationBuilder' => 'OrientationBuilder.svg',
    'PreferredSize' => 'PreferredSize.svg',
    'TabPageSelector' => 'TabPageSelector.svg',
    'TabPageSelectorIndicator' => 'TabPageSelectorIndicator.svg',
    'SafeArea' => 'SafeArea.svg',
    'Title' => 'Title.svg',
    'DecoratedSliver' => 'DecoratedSliver.svg',
    'PageStorage' => 'PageStorage.svg',
    'MaterialBanner' => 'MaterialBanner.svg',
    'HtmlElementView' => 'HtmlElementView.svg',
    'CheckedModeBanner' => 'CheckedModeBanner.svg',
    'NotificationListener' => 'NotificationListener.svg',
    'DraggableScrollableActuator' => 'DraggableScrollableActuator.svg',
    'FormField' => 'FormField.svg',
    'TweenAnimationBuilder' => 'TweenAnimationBuilder.svg',
    'DefaultTabController' => 'DefaultTabController.svg',
    'InputDecorator' => 'InputDecorator.svg',
    'Navigator' => 'Navigator.svg',
    'StatusTransitionWidget' => 'StatusTransitionWidget.svg',
    'WidgetInspector' => 'WidgetInspector.svg',
    'PaginatedDataTable' => 'PaginatedDataTable.svg',
    'WidgetsApp' => 'WidgetsApp.svg',
    'CarouselView' => 'CarouselView.svg',
    'AutomaticKeepAlive' => 'AutomaticKeepAlive.svg',
    'UndoHistory' => 'UndoHistory.svg',
    'StatefulBuilder' => 'StatefulBuilder.svg',
    'UniqueWidget' => 'UniqueWidget.svg',
    'TickerMode' => 'TickerMode.svg',
    'RawGestureDetector' => 'RawGestureDetector.svg',
    'GlowingOverscrollIndicator' => 'GlowingOverscrollIndicator.svg',
    'NestedScrollView' => 'NestedScrollView.svg',
    'DraggableScrollableSheet' => 'DraggableScrollableSheet.svg',
    'Scrollable' => 'Scrollable.svg',
    'RawKeyboardListener' => 'RawKeyboardListener.svg',
    'ValueListenableBuilder' => 'ValueListenableBuilder.svg',
    'DrawerController' => 'DrawerController.svg',
    'Badge' => 'Badge.svg',
    'MergeableMaterial' => 'MergeableMaterial.svg',
    'FractionalTranslation' => 'FractionalTranslation.svg',
    'RepaintBoundary' => 'RepaintBoundary.svg',
    'CompositedTransformFollower' => 'CompositedTransformFollower.svg',
    'CompositedTransformTarget' => 'CompositedTransformTarget.svg',
    'SliverMainAxisGroup' => 'SliverMainAxisGroup.svg',
    'SliverCrossAxisGroup' => 'SliverCrossAxisGroup.svg',
    'SliverConstrainedCrossAxis' => 'SliverConstrainedCrossAxis.svg',
    'SliverCrossAxisExpanded' => 'SliverCrossAxisExpanded.svg',
    'ShaderMask' => 'ShaderMask.svg',
    'BackdropFilter' => 'BackdropFilter.svg',
    'PhysicalShape' => 'PhysicalShape.svg',
    'TapRegion' => 'TapRegion.svg',
    'Focus' => 'Focus.svg',
    'CallbackShortcuts' => 'CallbackShortcuts.svg',
    'KeyboardListener' => 'KeyboardListener.svg',
    'CustomSingleChildLayout' => 'CustomSingleChildLayout.svg',
    'AbstractLayoutBuilder' => 'AbstractLayoutBuilder.svg',
    'LayoutBuilder' => 'LayoutBuilder.svg',
    'AnnotatedRegion' => 'AnnotatedRegion.svg',
    'RenderObjectToWidgetAdapter' => 'RenderObjectToWidgetAdapter.svg',
    'Localizations' => 'Localizations.svg',
    'ListWheelViewport' => 'ListWheelViewport.svg',
    'IgnorePointer' => 'IgnorePointer.svg',
    'MouseRegion' => 'MouseRegion.svg',
    'SizeChangedLayoutNotifier' => 'SizeChangedLayoutNotifier.svg',
    'AbsorbPointer' => 'AbsorbPointer.svg',
    'PhysicalModel' => 'PhysicalModel.svg',
    'IntrinsicWidth' => 'IntrinsicWidth.svg',
    'IntrinsicHeight' => 'IntrinsicHeight.svg',
    'SliverLayoutBuilder' => 'SliverLayoutBuilder.svg',
    'SliverIgnorePointer' => 'SliverIgnorePointer.svg',
    'SliverFillRemaining' => 'SliverFillRemaining.svg',
    'SliverOverlapAbsorber' => 'SliverOverlapAbsorber.svg',
    'SliverOverlapInjector' => 'SliverOverlapInjector.svg',
    'PinnedHeaderSliver' => 'PinnedHeaderSliver.svg',
    'ActionListener' => 'ActionListener.svg',
    'Actions' => 'Actions.svg',
    'PerformanceOverlay' => 'PerformanceOverlay.svg',
    'RawImage' => 'RawImage.svg',
    'SliverPrototypeExtentList' => 'SliverPrototypeExtentList.svg',
    'LayoutId' => 'LayoutId.svg',
    'KeepAlive' => 'KeepAlive.svg',
    'TableCell' => 'TableCell.svg',
    'Directionality' => 'Directionality.svg',
    'DefaultAssetBundle' => 'DefaultAssetBundle.svg',
    'AndroidView' => 'AndroidView.svg',
    'AndroidViewSurface' => 'AndroidViewSurface.svg',
    'MaterialBannerTheme' => 'MaterialBannerTheme.svg',
    'DividerTheme' => 'DividerTheme.svg',
    'PopupMenuTheme' => 'PopupMenuTheme.svg',
    'SliderTheme' => 'SliderTheme.svg',
    'TooltipTheme' => 'TooltipTheme.svg',
    'PrimaryScrollController' => 'PrimaryScrollController.svg',
    'InheritedModel' => 'InheritedModel.svg',
    'Viewport' => 'Viewport.svg',
    'CustomMultiChildLayout' => 'CustomMultiChildLayout.svg',
    'ListBody' => 'ListBody.svg',
    'ShrinkWrappingViewport' => 'ShrinkWrappingViewport.svg',
    'NestedScrollViewViewport' => 'NestedScrollViewViewport.svg',
    'InheritedTheme' => 'InheritedTheme.svg',
    'InheritedWidget' => 'InheritedWidget.svg',
    'ParentDataWidget' => 'ParentDataWidget.svg',
    'SliverWithKeepAliveWidget' => 'SliverWithKeepAliveWidget.svg',
    'ScrollView' => 'ScrollView.svg',
    'InteractiveViewer' => 'InteractiveViewer.svg',
    'ImageFiltered' => 'ImageFiltered.svg',
    'NavigationRail' => 'NavigationRail.svg',
    'RawMagnifier' => 'RawMagnifier.svg',
    'AppKitView' => 'AppKitView.svg',
    'AutocompleteHighlightedOption' => 'AutocompleteHighlightedOption.svg',
    'AutofillGroup' => 'AutofillGroup.svg',
    'BackdropGroup' => 'BackdropGroup.svg',
    'BadgeTheme' => 'BadgeTheme.svg',
    'BlockSemantics' => 'BlockSemantics.svg',
    'DropdownMenu' => 'DropdownMenu.svg',
    'CalendarDatePicker' => 'CalendarDatePicker.svg',
    'CardTheme' => 'CardTheme.svg',
    'CheckedPopupMenuItem' => 'CheckedPopupMenuItem.svg',
    'ConstrainedLayoutBuilder' => 'ConstrainedLayoutBuilder.svg',
    'DataTableTheme' => 'DataTableTheme.svg',
    'DatePickerTheme' => 'DatePickerTheme.svg',
    'DefaultSelectionStyle' => 'DefaultSelectionStyle.svg',
    'DisplayFeatureSubScreen' => 'DisplayFeatureSubScreen.svg',
    'DragBoundary' => 'DragBoundary.svg',
    'DrawerTheme' => 'DrawerTheme.svg',
    'DropdownMenuItem' => 'DropdownMenuItem.svg',
    'DropdownMenuTheme' => 'DropdownMenuTheme.svg',
    'DualTransitionBuilder' => 'DualTransitionBuilder.svg',
    'ExcludeFocus' => 'ExcludeFocus.svg',
    'ExcludeFocusTraversal' => 'ExcludeFocusTraversal.svg',
    'ExcludeSemantics' => 'ExcludeSemantics.svg',
    'Expansible' => 'Expansible.svg',
    'ExpansionTileTheme' => 'ExpansionTileTheme.svg',
    'FocusScope' => 'FocusScope.svg',
    'FocusTraversalGroup' => 'FocusTraversalGroup.svg',
    'FocusTraversalOrder' => 'FocusTraversalOrder.svg',
    'FocusableActionDetector' => 'FocusableActionDetector.svg',
    'HeroControllerScope' => 'HeroControllerScope.svg',
    'HeroMode' => 'HeroMode.svg',
    'IgnoreBaseline' => 'IgnoreBaseline.svg',
    'ImgElementPlatformView' => 'ImgElementPlatformView.svg',
    'IndexedSemantics' => 'IndexedSemantics.svg',
    'InheritedNotifier' => 'InheritedNotifier.svg',
    'InputDatePickerFormField' => 'InputDatePickerFormField.svg',
    'KeyedSubtree' => 'KeyedSubtree.svg',
    'LeafRenderObjectWidget' => 'LeafRenderObjectWidget.svg',
    'ListenableBuilder' => 'ListenableBuilder.svg',
    'LookupBoundary' => 'LookupBoundary.svg',
    'Magnifier' => 'Magnifier.svg',
    'MatrixTransition' => 'MatrixTransition.svg',
    'MenuAcceleratorCallbackBinding' => 'MenuAcceleratorCallbackBinding.svg',
    'MenuAcceleratorLabel' => 'MenuAcceleratorLabel.svg',
    'MenuAnchor' => 'MenuAnchor.svg',
    'MenuTheme' => 'MenuTheme.svg',
    'MergeSemantics' => 'MergeSemantics.svg',
    'MetaData' => 'MetaData.svg',
    'MultiChildRenderObjectWidget' => 'MultiChildRenderObjectWidget.svg',
    'NavigationDestination' => 'NavigationDestination.svg',
    'NavigationDrawer' => 'NavigationDrawer.svg',
    'NavigationDrawerDestination' => 'NavigationDrawerDestination.svg',
    'NavigationDrawerTheme' => 'NavigationDrawerTheme.svg',
    'NavigationIndicator' => 'NavigationIndicator.svg',
    'NavigationRailTheme' => 'NavigationRailTheme.svg',
    'NavigatorPopHandler' => 'NavigatorPopHandler.svg',
    'ObstructingPreferredSizeWidget' => 'ObstructingPreferredSizeWidget.svg',
    'OverlayPortal' => 'OverlayPortal.svg',
    'PlatformViewLink' => 'PlatformViewLink.svg',
    'PlatformViewSurface' => 'PlatformViewSurface.svg',
    'PopScope' => 'PopScope.svg',
    'PopupMenuEntry' => 'PopupMenuEntry.svg',
    'PopupMenuItem' => 'PopupMenuItem.svg',
    'PreferredSizeWidget' => 'PreferredSizeWidget.svg',
    'ProxyWidget' => 'ProxyWidget.svg',
    'RadioTheme' => 'RadioTheme.svg',
    'RawAutocomplete' => 'RawAutocomplete.svg',
    'RawMenuAnchor' => 'RawMenuAnchor.svg',
    'RawMenuAnchorGroup' => 'RawMenuAnchorGroup.svg',
    'RawView' => 'RawView.svg',
    'RawWebImage' => 'RawWebImage.svg',
    'RenderObjectWidget' => 'RenderObjectWidget.svg',
    'ReorderableDelayedDragStartListener' => 'ReorderableDelayedDragStartListener.svg',
    'ReorderableDragStartListener' => 'ReorderableDragStartListener.svg',
    'ReorderableList' => 'ReorderableList.svg',
    'RestorationScope' => 'RestorationScope.svg',
    'RootRestorationScope' => 'RootRestorationScope.svg',
    'RootWidget' => 'RootWidget.svg',
    'Router' => 'Router.svg',
    'ScaffoldMessenger' => 'ScaffoldMessenger.svg',
    'ScrollNotificationObserver' => 'ScrollNotificationObserver.svg',
    'SearchAnchor' => 'SearchAnchor.svg',
    'SearchViewTheme' => 'SearchViewTheme.svg',
    'SelectableRegion' => 'SelectableRegion.svg',
    'SelectableRegionSelectionStatusScope' => 'SelectableRegionSelectionStatusScope.svg',
    'SelectionArea' => 'SelectionArea.svg',
    'SelectionContainer' => 'SelectionContainer.svg',
    'SelectionListener' => 'SelectionListener.svg',
    'SelectionRegistrarScope' => 'SelectionRegistrarScope.svg',
    'Semantics' => 'Semantics.svg',
    'SemanticsDebugger' => 'SemanticsDebugger.svg',
    'SharedAppData' => 'SharedAppData.svg',
    'ShortcutRegistrar' => 'ShortcutRegistrar.svg',
    'Shortcuts' => 'Shortcuts.svg',
    'SingleChildRenderObjectWidget' => 'SingleChildRenderObjectWidget.svg',
    'SliverEnsureSemantics' => 'SliverEnsureSemantics.svg',
    'SliverFadeTransition' => 'SliverFadeTransition.svg',
    'SliverFloatingHeader' => 'SliverFloatingHeader.svg',
    'SliverOffstage' => 'SliverOffstage.svg',
    'SliverReorderableList' => 'SliverReorderableList.svg',
    'SliverResizingHeader' => 'SliverResizingHeader.svg',
    'SliverSafeArea' => 'SliverSafeArea.svg',
    'SliverVariedExtentList' => 'SliverVariedExtentList.svg',
    'Autocomplete' => 'Autocomplete.svg',
    'SlottedMultiChildRenderObjectWidget' => 'SlottedMultiChildRenderObjectWidget.svg',
    'SnapshotWidget' => 'SnapshotWidget.svg',
    'StatefulWidget' => 'StatefulWidget.svg',
    'StatelessWidget' => 'StatelessWidget.svg',
    'StreamBuilderBase' => 'StreamBuilderBase.svg',
    'StretchingOverscrollIndicator' => 'StretchingOverscrollIndicator.svg',
    'SwitchTheme' => 'SwitchTheme.svg',
    'TapRegionSurface' => 'TapRegionSurface.svg',
    'TimePickerTheme' => 'TimePickerTheme.svg',
    'TreeSliver' => 'TreeSliver.svg',
    'TwoDimensionalScrollView' => 'TwoDimensionalScrollView.svg',
    'TwoDimensionalScrollable' => 'TwoDimensionalScrollable.svg',
    'TwoDimensionalViewport' => 'TwoDimensionalViewport.svg',
    'UiKitView' => 'UiKitView.svg',
    'UnmanagedRestorationScope' => 'UnmanagedRestorationScope.svg',
    'View' => 'View.svg',
    'ViewAnchor' => 'ViewAnchor.svg',
    'ViewCollection' => 'ViewCollection.svg',
    _ => 'Widget.svg',
  };
}

class GlassSquare extends StatelessWidget {
  final Color color; // 主颜色
  final double size; // 边长
  final Widget? child; // 子组件

  const GlassSquare({
    super.key,
    required this.color,
    this.size = 300,
    this.child,
  });

  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(20),
      child: Stack(
        alignment: Alignment.center,
        children: [
          // 背景渐变层
          Container(
            width: size,
            height: size,
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [
                  color,
                  Color.lerp(color, Colors.white, 0.4)!,
                ],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withOpacity(0.4),
                  blurRadius: 25,
                  offset: const Offset(0, 8),
                ),
              ],
            ),
          ),

          // 毛玻璃效果层
          BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 18, sigmaY: 18),
            child: Container(
              width: size,
              height: size,
              decoration: BoxDecoration(
                border: Border.all(color: Colors.white.withOpacity(0.2)),
                color: Colors.white.withOpacity(0.05),
              ),
            ),
          ),

          // 高光层
          Container(
            width: size,
            height: size,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20),
              gradient: RadialGradient(
                colors: [
                  Colors.white.withOpacity(0.45),
                  Colors.transparent,
                ],
                radius: 0.6,
                center: const Alignment(-0.6, -0.6),
              ),
            ),
          ),

          // 柔光层
          Container(
            width: size,
            height: size,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(20),
              gradient: const LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [
                  Color.fromRGBO(255, 255, 255, 0.15),
                  Color.fromRGBO(0, 0, 0, 0.25),
                ],
              ),
            ),
          ),

          // 子组件
          if (child != null) child!,
        ],
      ),
    );
  }
}
